//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6758
        ///5199
        ///10292
        ///8812
        ///3527
        ///10178
        ///1340
        ///2824
        ///
        ///62522
        ///
        ///22990
        ///
        ///6730
        ///
        ///7255
        ///3210
        ///3003
        ///8296
        ///8799
        ///7655
        ///10312
        ///
        ///18837
        ///19882
        ///5386
        ///15891
        ///
        ///4203
        ///36288
        ///
        ///1586
        ///2295
        ///4981
        ///2109
        ///2284
        ///5814
        ///4823
        ///5492
        ///1524
        ///5286
        ///2147
        ///2952
        ///4783
        ///4814
        ///3042
        ///
        ///8474
        ///4059
        ///14465
        ///13390
        ///
        ///4623
        ///2150
        ///7545
        ///7833
        ///3686
        ///2095
        ///3336
        ///5030
        ///7648
        ///4087
        ///4482
        ///
        ///31278
        ///29863
        ///
        ///1228
        ///4851
        ///2706
        ///1692
        ///3200
        ///3521
        ///5200
        ///3755
        ///3922
        ///5181
        ///5561
        ///5162
        ///5280
        ///2460
        ///
        ///1083
        ///4432
        ///4938
        ///4303
        ///6304
        ///3746
        ///3527
        ///3141
        ///3198
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d1 {
            get {
                return ResourceManager.GetString("d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Z
        ///B Y
        ///C X
        ///B Z
        ///C Y
        ///B Y
        ///C Z
        ///C Z
        ///B Y
        ///B X
        ///C Y
        ///B Y
        ///B Z
        ///A Z
        ///A Y
        ///B X
        ///C Y
        ///C Z
        ///B Z
        ///A Y
        ///C Y
        ///C Z
        ///A Y
        ///C Z
        ///B X
        ///B Y
        ///B Y
        ///A Y
        ///C Z
        ///B Y
        ///B Y
        ///B Y
        ///C Z
        ///C Y
        ///B X
        ///C Y
        ///A Z
        ///C Y
        ///B X
        ///B Z
        ///C Z
        ///C Z
        ///B X
        ///A Y
        ///A Y
        ///C Z
        ///C Z
        ///C Z
        ///B Y
        ///C Y
        ///B Y
        ///C Z
        ///C Z
        ///A Z
        ///B Y
        ///C Y
        ///B X
        ///A Y
        ///C Y
        ///B Y
        ///C Z
        ///A Y
        ///B Y
        ///B Y
        ///B Y
        ///B Z
        ///C Y
        ///A X
        ///C Y
        ///B Y
        ///C Z
        ///A Z
        ///B X
        ///C Z
        ///C X
        ///A Y
        ///C Y
        ///B Z
        ///C Y
        ///C Z
        ///B X
        ///C Z
        ///C Y
        ///B Y
        ///B Y
        ///B Y
        ///B Y
        ///A Y
        ///C Z
        ///C Z
        ///B Y
        ///B Y
        ///C Z
        ///B Z
        ///B Y
        ///B Y
        ///B Y
        ///A Y
        ///B Z
        ///B Y
        ///C Y
        ///B X
        ///B  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d2 {
            get {
                return ResourceManager.GetString("d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mjpsHcssDzLTzMsz
        ///tFhbtClRVtbhRCGBFntNTrLhqrwqWMDMTWTqMq
        ///LltbngLGRSBgSgGRCJdSdQHvdfmQccmjSQ
        ///lBslsZDDWdGdGpSMts
        ///grQhDvqLQHDNGJJtbRMQQJ
        ///HChCTnnLCgCrTZPPFzzVPcVD
        ///ShrzjhNGrNqrhWnHHfVHbhnHbbhH
        ///RBsvcBcDCdsRTsvgCgcPFRQpVQGQJPVFbnJfbJ
        ///DvsTsdlCBsGLrjzmlqqz
        ///WJJqZTgCnBLGCZBJCJnTLggTDDSDDMNdDSdbdSSsWDFfMsFf
        ///PVjqpVHmPpvmcjhrRprFmQQffbfNbQMMsSMQNQ
        ///cwcpRvrVlVgwtBwZqBzZ
        ///qfJJmpqpmhsggvvpVPZCrhdFLFzZFDdLLh
        ///CtCTBctGcGLSzZddGZSW
        ///RlNjBCnjttBHHMMcQHCsRfsbfwgggmmJvmgfpm
        ///ZmcgBBZhZMsnqnCPjpHPjLHp
        ///dGbNwNtlTMTzGfNvTvdw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d3 {
            get {
                return ResourceManager.GetString("d3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22-77,14-96
        ///7-99,65-98
        ///22-36,37-62
        ///25-94,24-67
        ///6-91,1-6
        ///88-88,2-88
        ///27-89,58-96
        ///21-82,9-94
        ///38-79,27-80
        ///4-90,30-55
        ///84-97,52-93
        ///12-59,11-12
        ///4-14,5-12
        ///50-84,49-89
        ///3-98,1-3
        ///91-95,8-22
        ///15-66,17-67
        ///27-27,27-90
        ///36-37,37-96
        ///31-32,32-80
        ///1-79,2-78
        ///36-85,20-36
        ///2-2,2-98
        ///33-81,80-99
        ///4-73,45-72
        ///3-89,1-4
        ///6-92,21-91
        ///7-93,2-92
        ///47-89,47-50
        ///64-84,63-65
        ///22-85,21-91
        ///16-31,11-14
        ///4-93,3-93
        ///15-61,61-62
        ///21-23,22-88
        ///59-59,11-58
        ///23-23,22-89
        ///19-87,78-86
        ///13-82,19-83
        ///22-88,76-92
        ///46-47,46-46
        ///30-31, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d4 {
            get {
                return ResourceManager.GetString("d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [C]             [L]         [T]
        ///    [V] [R] [M]     [T]         [B]
        ///    [F] [G] [H] [Q] [Q]         [H]
        ///    [W] [L] [P] [V] [M] [V]     [F]
        ///    [P] [C] [W] [S] [Z] [B] [S] [P]
        ///[G] [R] [M] [B] [F] [J] [S] [Z] [D]
        ///[J] [L] [P] [F] [C] [H] [F] [J] [C]
        ///[Z] [Q] [F] [L] [G] [W] [H] [F] [M]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 1 from 5 to 6
        ///move 5 from 6 to 7
        ///move 10 from 7 to 3
        ///move 4 from 8 to 4
        ///move 2 from 5 to 4
        ///move 4 from 3 to 6
        ///move 6 from 2 to 4
        ///move 8 from 6 to 9
        ///move 5 from 9 to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d5 {
            get {
                return ResourceManager.GetString("d5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzsspbssbhshchmmrmprmrfrsfrrjhjphjjtppbfflqfqppdhdbhdhbbjgghgzgsgfsfhfhvvwcwhwwnppsbsggqnnvvtffpssjfjnnltntdtdddptprppjmmqssrlrplllfrrzggbmmlmnmtnnzddfdgfdfsstbstbbzcbbcjcvvfwwwzlzssglsgllnbnmbnmbbgmmppmwwsrrzqqvgqgnqnmmswwrnnbsnnbdbwwqnwqnwwzzqwzqzjqqwbqbccjcwwjlwjwppqfqjffwddrzrjzrjzzzhchjjlqqrggzvvnlvnvjvhvnvjvbbvdvldldbbwddtsscbbhccmbmbppbmmgjggcjjlrrwjwtjwwmffgddwvdvbdbvvhchmhmdmwwbjbjcbbcmbmmslmlslsjjrnrjrjpjcjgcjcjbbwsbsbfssjzsjsggcmcsswgssbbqpbqqdsdqqztzmzpmpbmbvbjjtrjtthwhbhnbhnbnssvpvsppgrrcwrrmqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d6 {
            get {
                return ResourceManager.GetString("d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir gqcclj
        ///dir lmtpm
        ///dir nhqwt
        ///dir qcq
        ///dir vwqwlqrt
        ///$ cd gqcclj
        ///$ ls
        ///62425 dqp.gjm
        ///174181 hrtw.qsd
        ///273712 pflp.mdw
        ///169404 zlthnlhf.mtn
        ///180878 zprprf
        ///$ cd ..
        ///$ cd lmtpm
        ///$ ls
        ///dir clffsvcw
        ///163587 cvcl.jqh
        ///dir dcqnblb
        ///dir dtpwln
        ///dir fvt
        ///dir hrcrw
        ///dir jdqzmqn
        ///236754 nrdmlj
        ///205959 pflp.mdw
        ///dir qcq
        ///dir rsn
        ///129926 vdgcqdn.sqd
        ///dir zprprf
        ///$ cd clffsvcw
        ///$ ls
        ///6997 dcqnblb.wbh
        ///145711 dqp
        ///159225 pflp.mdw
        ///$ cd ..
        ///$ cd dcqnblb
        ///$ ls
        ///dir dcqnblb
        ///dir gfn
        ///dir lpswsp
        ///dir lvt        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d7 {
            get {
                return ResourceManager.GetString("d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir a
        ///14848514 b.txt
        ///8504156 c.dat
        ///dir d
        ///$ cd a
        ///$ ls
        ///dir e
        ///29116 f
        ///2557 g
        ///62596 h.lst
        ///$ cd e
        ///$ ls
        ///584 i
        ///$ cd ..
        ///$ cd ..
        ///$ cd d
        ///$ ls
        ///4060174 j
        ///8033020 d.log
        ///5626152 d.ext
        ///7214296 k
        ///.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
